config/routes.rb
Rails.application.routes.draw do

  ActiveAdmin.routes(self)
  devise_for :users

  scope '(:locale)', locale: /fr/ do

    root to: "home#index"

    get 'dashboards/index', path: 'dashboard'

    resources :tracks

    resources :exercises do
      resources :sessions
    end

  end

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :question
  belongs_to :session
  belongs_to :user
  belongs_to :exercise

  has_attached_file :photo,
    styles: { moodboard: "200x200>" }

  validates_attachment_content_type :photo,
    content_type: /\Aimage\/.*\z/

  validates_presence_of :user_id, :session_id, :question_id, :exercise_id, :original_question

end

app/models/exercise.rb
class Exercise < ActiveRecord::Base
  belongs_to :track
  has_many :questions
  has_many :sessions
  has_many :answers

  has_attached_file :photo,
    styles: { medium: "200x200#", thumb: "100x100>" }

  validates_attachment_content_type :photo,
    content_type: /\Aimage\/.*\z/

  validates_presence_of :title, :description, :track_id, :position
end

app/models/exo_sessions.rb
class ExoSessions < ActiveRecord::Base
end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :exercise
  has_many :answers

  has_attached_file :photo,
    styles: { medium: "200x200#", thumb: "100x100>" }

  validates_attachment_content_type :photo,
    content_type: /\Aimage\/.*\z/


  validates_presence_of :title, :description, :exercise_id, :position
end

app/models/session.rb
class Session < ActiveRecord::Base
  belongs_to :exercise
  belongs_to :user

  has_many :answers
  has_one :track, through: :exercise
  accepts_nested_attributes_for :answers

  validates_presence_of :user_id, :exercise_id

end

app/models/track.rb
class Track < ActiveRecord::Base
  has_many :exercises

  has_attached_file :photo,
    styles: { medium: "200x200#", thumb: "100x100>" }

  validates_attachment_content_type :photo,
    content_type: /\Aimage\/.*\z/

  validates_presence_of :title, :description, :position

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :answers
  has_many :sessions

  has_attached_file :picture,
    styles: { profile: "100x100#", nav: "30x30#" }, :default_url => "http://placehold.it/200&text=user"

  validates_attachment_content_type :picture,
    content_type: /\Aimage\/.*\z/

  validates_presence_of :email, :encrypted_password


  def exercises
    self.sessions.map{ |session| session.exercise }.uniq
  end


  def last_sessions(session)
    track = session.track
    exercises_in_track = self.exercises.select { |e| e.track_id == track.id && e.position != session.exercise.position }

    grouped_exercises = exercises_in_track.group_by { |e| e.position }
    grouped_exercises.map do |position, exercises|
      exercises.last.sessions.order(:updated_at).limit(1).last
    end
  end

  private

  def send_welcome_email
    UserMailer.welcome(self).deliver
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  def index
  end

  def show
  end

  def new
  end

  def create
  end

  def update
  end

  def edit
  end

  def destroy
  end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  def index
    @user = current_user
  end
end

app/controllers/exercises_controller.rb
class ExercisesController < ApplicationController

  def edit

  end

  private
  def exercise_params
    params.require(:exercise).permit(:title, :description, :photo)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :authenticate_user!

  def index
    @tracks = Track.all
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def show
    # @question = Question.find(params[:id])
  end

  private
  def track_params
    params.require(:question).permit(:title, :description, :photo)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :set_exercise

  def new
    @user = current_user
    @previous_sessions = @exercise.sessions.where(user: current_user)
    @session = @exercise.sessions.new
    @exercises = @exercise.questions.each do |question|
      @session.answers.new(question: question)
    end
    # @exercises.questions.order(:position)
  end

  def create
    @session = @exercise.sessions.new
    @session.user = current_user

    if @session.save
      @exercise.questions.each do |question|
        answer = @session.answers.new(exercise: @exercise, question: question, session: @session, user: current_user, original_question: question.title)
        answer.content = params[:session][:answers_attributes][(answer.question.position - 1).to_s][:content]
      end

      if @session.save
       redirect_to track_path(@exercise.track)
      else
        render :new
      end
    end
  end

  def edit
    @session = Session.find(params[:id])
  end

  def update
    @session = Session.find(params[:id])

    if @session.update(session_params)
      redirect_to dashboards_index_path
    else
      render :edit, notice: 'An error occurred, please try again.'
    end
  end



  def index
    #list of all done exercises
    @sessions = @exercise.sessions
  end

  def destroy
    @session = Session.find(params[:id])
    @session.destroy
    redirect_to dashboards_index_path, notice: 'Exercise was successfully deleted.'
  end


  private

    def set_exercise
      @exercise = Exercise.find(params[:exercise_id])
    end

    def session_params
      params.require(:session).permit(answers_attributes: [ :original_question, :content, :question_id, :exercise_id ])
    end

end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController
  before_action :authenticate_user!, only: [:show]

  def index
    @tracks = Track.all
  end

  def show
    @track = Track.find(params[:id])
    @exercises = @track.exercises.order(:position)
  end

  def new

  end

  private
  def track_params
    params.require(:track).permit(:title, :description, :photo)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end

  def show
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  skip_before_action :authenticate_user!

  def index
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end

end

app/helpers/exercise_helper.rb
module ExerciseHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/track_helper.rb
module TrackHelper
end

app/views/dashboards/_progressbar.html.erb
<div class="progress">
  <div class="progress-bar" role="progressbar" aria-valuenow="2" aria-valuemin="0" aria-valuemax="100" style="width: 2%;">
    2%
  </div>
</div>

app/views/dashboards/index.html.erb
<div class="container text-center">
  <div class="row">
    <div class="col-xs-8 col-xs-offset-2">
      <div class="page-header">
        <h1 class="color-red"><%= t '.title' %></h1>
      </div>
      <div class="img-fit">
        <%= image_tag current_user.picture(:profile), class:"pic-dashboard" %>
      </div>
      <div id="identity">
        <h3><%= current_user.first_name%>  <%= current_user.last_name%></h3>
      </div>
    </div>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="col-xs-7 col-xs-offset-2">
      <% if @user.exercises.size > 0 %>
        <h1><%= t '.header1' %></h1>
        <% current_track = nil %>
        <% @user.exercises.each do |exercise| %>
        <% if current_track != exercise.track %>
          <h3><%= exercise.track.title %></h3>
        <% end %>
        <%= render "progressbar" %>
          <h4><%= exercise.title %></h4>
          <% @user.sessions.where(exercise_id: exercise.id).each do |session| %>
            <p><%= link_to "Last update: #{session.updated_at}", edit_exercise_session_path(exercise, session) %></p>
            <%= link_to "View", edit_exercise_session_path(exercise, session), class:"btn btn-sm btn-primary" %>
            <%= link_to "Delete", exercise_session_path(exercise, session), method: :delete,
              data: { confirm: "Are you sure?" }, class:"btn btn-sm btn-danger" %>
          <% end %>
        <% end %>
      <% end %>
      <br>
      <br>
    </div>
      <div class="col-xs-6 col-xs-offset-2">
        <div class="actions">
          <%= link_to "Back to tracks", tracks_path, class:"btn btn-lg btn-exo" %>
      </div>
    </div>

  </div>
</div>

<div class="container">
  <div class="row">
    <div class="col-xs-7 col-xs-offset-2">
      <h1><%= t '.header2' %></h1>
    </div>
  </div>
</div>

app/views/home/index.html.erb
<div class="wrapper" id="header">

<div class="container">
  <div class="row">
      <div class="col-sm-12 text-center text-title">
        <h1><%= t '.title' %></h1>
        <h2><small>Lorem ipsum dolor sit amet!</small></h2>
    </div>
    <div class="col-sm-offset-1 col-sm-10 col-xs-12 homebanner">
      <div class="row">
        <div class="col-xs-12 col-sm-offset-2 col-sm-8 col-md-offset-1 col-md-6">

            <% if user_signed_in? %>
            <div class="col-sm-2 col-sm-offset-2" id="home_track">
              <h1><%= t '.header' %></h1>
              <% @tracks.each do |track| %>
              <h2><%= link_to track.title, track %></h2>
              <p><%= track.description %></p>
              <% end %>
            </div>
            <% else %>
            <%= render "devise/registrations/new" %>
            <% end %>

        </div>
      </div>
    </div>
  </div>
</div>
</div>